// <auto-generated />
using System;
using CoreBanking.Products.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CoreBanking.Products.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SavingsProductsWriteDbContext))]
    [Migration("20260606183413_InitialProducts")]
    partial class InitialProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PRODUCTS")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreBanking.BuildingBlocks.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AggregateKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("OUTBOX_MESSAGES", "PRODUCTS");
                });

            modelBuilder.Entity("CoreBanking.Products.Domain.SavingsProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CREATEDONUTC");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LASTMODIFIEDBY");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("LASTMODIFIEDONUTC");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SHORTNAME");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUSENUM");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.ToTable("SAVINGS_PRODUCTS", "PRODUCTS");
                });

            modelBuilder.Entity("CoreBanking.Products.Domain.SavingsProduct", b =>
                {
                    b.OwnsOne("CoreBanking.Products.Domain.Currency", "Currency", b1 =>
                        {
                            b1.Property<Guid>("SavingsProductId")
                                .HasColumnType("RAW(16)");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("NVARCHAR2(3)")
                                .HasColumnName("CURRENCYCODE");

                            b1.Property<int>("DecimalPlaces")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("CURRENCYDECIMALPLACES");

                            b1.HasKey("SavingsProductId");

                            b1.ToTable("SAVINGS_PRODUCTS", "PRODUCTS");

                            b1.WithOwner()
                                .HasForeignKey("SavingsProductId");
                        });

                    b.OwnsOne("CoreBanking.Products.Domain.InterestSettings", "InterestSettings", b1 =>
                        {
                            b1.Property<Guid>("SavingsProductId")
                                .HasColumnType("RAW(16)");

                            b1.Property<int>("CalculationType")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("CALCULATIONTYPE");

                            b1.Property<int>("CompoundingPeriod")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("COMPOUNDINGPERIOD");

                            b1.Property<int>("DaysInYearType")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("DAYSINYEARTYPE");

                            b1.Property<decimal>("NominalAnnualRate")
                                .HasColumnType("NUMBER(18,6)")
                                .HasColumnName("NOMINALANNUALRATE");

                            b1.Property<int>("PostingPeriod")
                                .HasColumnType("NUMBER(10)")
                                .HasColumnName("POSTINGPERIOD");

                            b1.HasKey("SavingsProductId");

                            b1.ToTable("SAVINGS_PRODUCTS", "PRODUCTS");

                            b1.WithOwner()
                                .HasForeignKey("SavingsProductId");
                        });

                    b.Navigation("Currency")
                        .IsRequired();

                    b.Navigation("InterestSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
