// <auto-generated />
using System;
using CoreBanking.Accounts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CoreBanking.Accounts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SavingsAccountsWriteDbContext))]
    [Migration("20260606184750_InitialSavings")]
    partial class InitialSavings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SAVINGS")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreBanking.Accounts.Application.ReadModels.ClientRef", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<long>("EventVersion")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("EVENTVERSION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.HasKey("ClientId");

                    b.ToTable("CLIENT_REF", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.Accounts.Application.ReadModels.ProductRef", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("CURRENCYCODE");

                    b.Property<int>("CurrencyDecimalPlaces")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CURRENCYDECIMALPLACES");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("DEFAULTRATE");

                    b.Property<long>("EventVersion")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("EVENTVERSION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.HasKey("ProductId");

                    b.ToTable("PRODUCT_REF", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.Accounts.Domain.SavingsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ACCOUNTNO");

                    b.Property<string>("ActivatedOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIVATEDON");

                    b.Property<string>("ApprovedOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("APPROVEDON");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CLIENTID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CREATEDONUTC");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("CURRENCYCODE");

                    b.Property<int>("CurrencyDecimalPlaces")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CURRENCYDECIMALPLACES");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LASTMODIFIEDBY");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("LASTMODIFIEDONUTC");

                    b.Property<decimal>("NominalAnnualRate")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("NOMINALANNUALRATE");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PRODUCTID");

                    b.Property<string>("RejectedOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("REJECTEDON");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUSENUM");

                    b.Property<string>("SubmittedOn")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("SUBMITTEDON");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSION");

                    b.Property<string>("WithdrawnOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("WITHDRAWNON");

                    b.HasKey("Id");

                    b.HasIndex("AccountNo")
                        .IsUnique();

                    b.ToTable("SAVINGS_ACCOUNTS", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.BuildingBlocks.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset>("ReceivedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EventId");

                    b.ToTable("INBOX_MESSAGES", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.BuildingBlocks.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AggregateKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("OUTBOX_MESSAGES", "SAVINGS");
                });
#pragma warning restore 612, 618
        }
    }
}
