// <auto-generated />
using System;
using CoreBanking.Accounts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CoreBanking.Accounts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SavingsAccountsWriteDbContext))]
    [Migration("20260629230054_AddAccountTransfers")]
    partial class AddAccountTransfers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SAVINGS")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SAVINGS_ACCOUNT_NO_SEQ", "SAVINGS");

            modelBuilder.Entity("CoreBanking.Accounts.Application.ReadModels.ClientRef", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<long>("EventVersion")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("EVENTVERSION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.HasKey("ClientId");

                    b.ToTable("CLIENT_REF", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.Accounts.Application.ReadModels.ProductRef", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("CURRENCYCODE");

                    b.Property<int>("CurrencyDecimalPlaces")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CURRENCYDECIMALPLACES");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("DEFAULTRATE");

                    b.Property<long>("EventVersion")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("EVENTVERSION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.HasKey("ProductId");

                    b.ToTable("PRODUCT_REF", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.Accounts.Domain.AccountTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(19,6)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("ClientTransferReference")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CLIENTTRANSFERREFERENCE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CREATEDONUTC");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("CURRENCYCODE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("DESTINATIONACCOUNTID");

                    b.Property<Guid>("DestinationTransactionId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("DESTINATIONTRANSACTIONID");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LASTMODIFIEDBY");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("LASTMODIFIEDONUTC");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SOURCEACCOUNTID");

                    b.Property<Guid>("SourceTransactionId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SOURCETRANSACTIONID");

                    b.Property<string>("TransferDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TRANSFERDATE");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("ClientTransferReference")
                        .IsUnique()
                        .HasDatabaseName("IX_ACCOUNT_TRANSFERS_CLIENTTRANSFERREFERENCE");

                    b.HasIndex("DestinationTransactionId")
                        .HasDatabaseName("IX_ACCOUNT_TRANSFERS_DESTINATIONTRANSACTIONID");

                    b.HasIndex("SourceTransactionId")
                        .HasDatabaseName("IX_ACCOUNT_TRANSFERS_SOURCETRANSACTIONID");

                    b.ToTable("ACCOUNT_TRANSFERS", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.Accounts.Domain.SavingsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("NUMBER(19,6)")
                        .HasColumnName("ACCOUNTBALANCE");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ACCOUNTNO");

                    b.Property<string>("ActivatedOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ACTIVATEDON");

                    b.Property<string>("ApprovedOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("APPROVEDON");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CLIENTID");

                    b.Property<string>("ClosedOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CLOSEDON");

                    b.Property<int>("Compounding")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COMPOUNDINGENUM");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("CREATEDONUTC");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("CURRENCYCODE");

                    b.Property<int>("CurrencyDecimalPlaces")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CURRENCYDECIMALPLACES");

                    b.Property<int>("DaysInYear")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DAYSINYEARENUM");

                    b.Property<string>("InterestPostedTillDate")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("INTERESTPOSTEDTILLDATE");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LASTMODIFIEDBY");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE")
                        .HasColumnName("LASTMODIFIEDONUTC");

                    b.Property<decimal>("NominalAnnualRate")
                        .HasColumnType("NUMBER(18,6)")
                        .HasColumnName("NOMINALANNUALRATE");

                    b.Property<int>("PostingPeriod")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POSTINGPERIODENUM");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PRODUCTID");

                    b.Property<string>("RejectedOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("REJECTEDON");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUSENUM");

                    b.Property<string>("SubmittedOn")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("SUBMITTEDON");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSION");

                    b.Property<string>("WithdrawnOn")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("WITHDRAWNON");

                    b.HasKey("Id");

                    b.HasIndex("AccountNo")
                        .IsUnique();

                    b.ToTable("SAVINGS_ACCOUNTS", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.Accounts.Domain.SavingsAccountTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ACCOUNTID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(19,6)")
                        .HasColumnName("AMOUNT");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("NUMBER(19,6)")
                        .HasColumnName("RUNNINGBALANCE");

                    b.Property<int>("Sequence")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SEQUENCENO");

                    b.Property<string>("TransactionDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("TRANSACTIONDATE");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPEENUM");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "TransactionDate");

                    b.ToTable("SAVINGS_ACCOUNT_TRANSACTIONS", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.BuildingBlocks.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset>("ReceivedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EventId");

                    b.ToTable("INBOX_MESSAGES", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.BuildingBlocks.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AggregateKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("CLOB");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("OUTBOX_MESSAGES", "SAVINGS");
                });

            modelBuilder.Entity("CoreBanking.Accounts.Domain.SavingsAccountTransaction", b =>
                {
                    b.HasOne("CoreBanking.Accounts.Domain.SavingsAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreBanking.Accounts.Domain.SavingsAccount", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
