#!/bin/bash
set -e

sqlplus -S SYS/"${ORACLE_PASSWORD}"@localhost:1521/FREEPDB1 as SYSDBA <<EOF
CREATE USER CLIENTS IDENTIFIED BY "${ORACLE_PASSWORD}"
  DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO CLIENTS;

CREATE USER PRODUCTS IDENTIFIED BY "${ORACLE_PASSWORD}"
  DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO PRODUCTS;

CREATE USER SAVINGS IDENTIFIED BY "${ORACLE_PASSWORD}"
  DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SAVINGS;
EXIT;
EOF
